language: node_js
node_js:
  - "7"
  - "9"
before_script:
  - "npm install"
  - "git pull origin master"
script:
  - "npm test"
after_script:
  - mongo oink_dev --eval 'db.User.remove({"username":"test"})"'
  - mongo oink_dev --eval 'db.Transaction.remove({"paidBy":"test"})"'
  - mongo oink_dev --eval 'db.Bill.remove({"splitWith":"test"})"'
  - mongo oink_dev --eval 'db.Group.remove({"name":"test"})"'
  - mongo oink_dev --eval 'db.Friend.remove({"balance":-1000000})"'
notifications:
  slack:
    rooms:
      - nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt#group_oink
      - nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt#travis-results
